name: LMdiff
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip>=20.0.0
#  - jupyter
#  - nb_conda
  - pytest
  - mypy
  - black
  - pip:
    - fastapi[all]
    - pydantic
    - spacy
    - gunicorn==20.1.0
    - dvc[s3]==2.1.0
    - regex==2021.4.4
    - numpy==1.20.3
    - sentencepiece==0.1.95
    - transformers==4.6.0
    - torch==1.8.1

